# Generated by Django 2.2.24 on 2021-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomacy', models.IntegerField()),
                ('cooperation', models.IntegerField()),
                ('honesty', models.IntegerField()),
                ('nerve', models.IntegerField()),
                ('openness', models.IntegerField()),
            ],
        ),
    ]
