# Generated by Django 2.2.24 on 2021-09-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.AddField(
            model_name='personal',
            name='login_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myApp.login'),
            preserve_default=False,
        ),
    ]
