# Generated by Django 2.2.24 on 2021-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210928_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q9',
            field=models.IntegerField(),
        ),
    ]
