# Generated by Django 2.2.24 on 2021-10-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210928_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='user',
        ),
        migrations.AddField(
            model_name='personal',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myApp.question'),
            preserve_default=False,
        ),
    ]
