# Generated by Django 2.2.24 on 2021-10-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20211002_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='question_ptr',
        ),
        migrations.AddField(
            model_name='personal',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.login'),
            preserve_default=False,
        ),
    ]
