# Generated by Django 2.2.24 on 2021-08-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('mail', models.TextField()),
                ('birth', models.CharField(max_length=8)),
                ('school_name', models.TextField()),
                ('school_grade', models.CharField(max_length=1)),
                ('sexuality', models.TextField()),
                ('insta_ID', models.TextField()),
                ('twitter_ID', models.TextField()),
                ('SNS_name1', models.TextField()),
                ('SNS_ID1', models.TextField()),
                ('SNS_name2', models.TextField()),
                ('SNS_ID2', models.TextField()),
            ],
        ),
    ]
