# Generated by Django 2.2.24 on 2021-09-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(default='photos/photo_initial.jpeg', upload_to='photos/')),
                ('photo2', models.ImageField(default='photos/photo_initial.jpeg', upload_to='photos/')),
                ('photo3', models.ImageField(default='photos/photo_initial.jpeg', upload_to='photos/')),
                ('photo4', models.ImageField(default='photos/photo_initial.jpeg', upload_to='photos/')),
                ('photo5', models.ImageField(default='photos/photo_initial.jpeg', upload_to='photos/')),
                ('photo6', models.ImageField(default='photos/photo_initial.jpeg', upload_to='photos/')),
                ('heart', models.BooleanField(default=False)),
                ('profile_text', models.TextField(blank=True, null=True)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.login')),
            ],
        ),
    ]
