# Generated by Django 2.2.24 on 2021-09-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby',
            new_name='hobby1',
        ),
        migrations.AddField(
            model_name='hobby',
            name='hobby2',
            field=models.CharField(choices=[('スポーツ', 'スポーツ'), ('読書', '読書')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobby',
            name='hobby3',
            field=models.CharField(choices=[('スポーツ', 'スポーツ'), ('読書', '読書')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
