# Generated by Django 2.2.24 on 2021-08-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_login_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='SNS_ID1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='SNS_ID2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='SNS_name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='SNS_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='insta_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='mail',
            field=models.EmailField(max_length=240),
        ),
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='sexuality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='twitter_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
