# Generated by Django 2.2.24 on 2021-09-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210915_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='school_major',
            field=models.CharField(choices=[('1', '文系（教育、美術、言語、文学、音楽、心理学）'), ('2', '社会・法学系（国際、法律、政治、社会学）'), ('3', '会計学・ビジネス・経済学・財政学・マーケティング・貿易'), ('4', '科学（農業、コンピュータ・サイエンス、数学、物理学、統計学）'), ('5', '保険・医療（医学、看護、薬学、公衆衛生）'), ('6', '工学・建築'), ('7', 'その他')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby2',
            field=models.CharField(blank=True, choices=[('スポーツ', 'スポーツ'), ('読書', '読書')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby3',
            field=models.CharField(blank=True, choices=[('スポーツ', 'スポーツ'), ('読書', '読書')], max_length=5, null=True),
        ),
    ]
