# Generated by Django 2.2.24 on 2021-08-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210816_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(blank=True, default='media/imeges/initial.jpeg', null=True, upload_to='media/images/'),
        ),
    ]
