# Generated by Django 2.2.24 on 2021-09-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210915_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='login_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby2',
            field=models.CharField(blank=True, choices=[('スポーツ', 'スポーツ'), ('読書', '読書')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby3',
            field=models.CharField(blank=True, choices=[('スポーツ', 'スポーツ'), ('読書', '読書')], max_length=5, null=True),
        ),
    ]
