# Generated by Django 2.2.24 on 2021-08-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210816_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(blank=True, default='media/images/initial.jpeg', null=True, upload_to='media/images/'),
        ),
    ]
