# Generated by Django 2.2.24 on 2021-09-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210921_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='login_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.login'),
        ),
    ]
