# Generated by Django 2.2.24 on 2021-09-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210928_1336'),
        ('myApp', '0005_auto_20210921_1714'),
    ]

    operations = [
    ]
