# Generated by Django 2.2.24 on 2021-08-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210816_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(default='media/images/initial.jpeg', upload_to='media/images/'),
        ),
    ]
