# Generated by Django 2.2.24 on 2021-09-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210921_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='login_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby1',
            field=models.CharField(choices=[('スポーツ', 'スポーツ'), ('読書', '読書'), ('旅行', '旅行'), ('カメラ', 'カメラ'), ('映画鑑賞', '映画鑑賞')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby2',
            field=models.CharField(blank=True, choices=[('スポーツ', 'スポーツ'), ('読書', '読書'), ('旅行', '旅行'), ('カメラ', 'カメラ'), ('映画鑑賞', '映画鑑賞')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby3',
            field=models.CharField(blank=True, choices=[('スポーツ', 'スポーツ'), ('読書', '読書'), ('旅行', '旅行'), ('カメラ', 'カメラ'), ('映画鑑賞', '映画鑑賞')], max_length=5, null=True),
        ),
    ]
