# Generated by Django 2.2.24 on 2021-08-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210816_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='picture',
            field=models.ImageField(default='images/initial.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='school_grade',
            field=models.CharField(choices=[('1', '1年生'), ('2', '2年生'), ('3', '3年生'), ('4', '4年生'), ('大学院', '大学院生')], max_length=1),
        ),
        migrations.AlterField(
            model_name='login',
            name='sexuality',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('その他', 'その他')], max_length=5),
        ),
    ]
