# Generated by Django 2.2.24 on 2021-10-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_personal_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_user', models.CharField(blank=True, max_length=50, null=True)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.login')),
            ],
        ),
    ]
