# Generated by Django 2.2.24 on 2021-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210824_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(choices=[('スポーツ', 'スポーツ'), ('読書', '読書')], max_length=5)),
            ],
        ),
    ]
