# Generated by Django 2.2.24 on 2021-10-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20211015_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='heart_check',
            field=models.BooleanField(default=False),
        ),
    ]
