# Generated by Django 2.2.24 on 2021-11-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_heart_heart_check'),
        ('myApp', '0010_auto_20211109_1622'),
    ]

    operations = [
    ]
