# Generated by Django 2.2.24 on 2021-11-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='post',
            name='receiver',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
