# Generated by Django 2.2.24 on 2021-11-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20211123_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.CharField(max_length=1),
        ),
    ]
