# Generated by Django 2.2.24 on 2021-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20211123_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='receiver',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.CharField(max_length=4),
        ),
    ]
