# Generated by Django 2.2.24 on 2021-11-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20211126_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='senduser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.login'),
            preserve_default=False,
        ),
    ]
