# Generated by Django 2.2.24 on 2021-11-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
