# Generated by Django 2.2.24 on 2021-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20211127_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='receiver',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.CharField(max_length=5),
        ),
    ]
